# Generated by Django 2.1.14 on 2020-01-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/studio', verbose_name='Картинка поста')),
                ('date_posting', models.DateTimeField(verbose_name='Дата')),
                ('moderation', models.IntegerField(verbose_name='Модерация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
