# Generated by Django 2.1.14 on 2020-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='connect_result',
            new_name='facebook_result',
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_result',
            field=models.BooleanField(default=False),
        ),
    ]
