# Generated by Django 2.1.14 on 2020-01-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posting',
            field=models.DateTimeField(blank=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderation',
            field=models.IntegerField(blank=True, verbose_name='Модерация'),
        ),
    ]
