# Generated by Django 2.1.14 on 2020-03-10 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialNetworkFacebook',
            new_name='SocialNetworkLiveJournal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sn_facebook',
            new_name='sn_lj',
        ),
    ]
