# Generated by Django 2.1.14 on 2020-01-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20200102_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка поста'),
        ),
    ]
