# Generated by Django 2.1.14 on 2020-01-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20200102_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='studio/'),
        ),
    ]
