# Generated by Django 2.1.14 on 2020-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_statistic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='facebook_result',
            new_name='live_journal_result',
        ),
        migrations.AddField(
            model_name='post',
            name='live_journal_task_id',
            field=models.UUIDField(),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_task_id',
            field=models.UUIDField(),
        ),
    ]
