# Generated by Django 2.1.14 on 2020-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20200102_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='E:\\Django\\Auto_posting_service\\media'),
        ),
    ]
