# Generated by Django 2.1.14 on 2020-01-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_auto_20200110_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('connect_result', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.SocialNetwork')),
            ],
        ),
    ]
