# Generated by Django 2.1.14 on 2020-01-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_socialnetworkfacebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_channel', models.CharField(max_length=256)),
                ('connect_result', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.SocialNetwork')),
            ],
        ),
    ]
