# Generated by Django 2.1.14 on 2020-01-10 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_socialnetworktelegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='moderation',
        ),
        migrations.AddField(
            model_name='post',
            name='connect_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='date_post_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='post',
            name='sn_facebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.SocialNetworkFacebook'),
        ),
        migrations.AddField(
            model_name='post',
            name='sn_telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.SocialNetworkTelegram'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата час коли викласти'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='E:\\Django\\Auto_posting_service\\media', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
