# Generated by Django 2.1.14 on 2020-04-04 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0009_auto_20200329_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_text', models.TextField(max_length=256, verbose_name='Краткий текст')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='E:\\Django\\Auto_posting_service\\media', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status_read', models.BooleanField(default=True, verbose_name='status_read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
