# Generated by Django 2.1.14 on 2020-04-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_auto_20200404_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date when posting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='E:\\Django\\Auto_posting_service\\media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='post_create',
            field=models.IntegerField(default=0, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='photo',
            field=models.ImageField(upload_to='E:\\Django\\Auto_posting_service\\media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='short_text',
            field=models.TextField(max_length=180, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='status_read',
            field=models.BooleanField(default=False, verbose_name='status read'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
